GET http://localhost:5000/home

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "firstName": "Milos",
    "lastName": "Ilic",
    "email": "milosilic1@gmail.com",
    "password": "milos12345"
}

###

DELETE http://localhost:5000/todo/delete/6429c94cfa263cea1735d080

###

PUT http://localhost:5000/todo/complete/6429c8baa8ba27ec9b2acc99